Changes footer link color
dwolfand/pay-it-furloughed-trender pull request #3
Opened 2019-01-17 23:17 UTC by JamesIves

Footer link wasn't really visible due to the background.

**Before:**

<img width="674" alt="screen shot 2019-01-17 at 6 16 18 pm" src="https://user-images.githubusercontent.com/10888441/51355123-0bf32480-1a84-11e9-9015-feb0e9b1e519.png">

**After:**
<img width="684" alt="screen shot 2019-01-17 at 6 16 32 pm" src="https://user-images.githubusercontent.com/10888441/51355129-131a3280-1a84-11e9-8892-7a6f6274c126.png">

2019-01-18 08:26 UTC, dwolfand requested changes

2019-01-18 08:26 UTC, dwolfand commented on client/src/App.js
> +          <footer>Data from <a target="_blank" rel="noopener noreferrer" href="https://payitfurloughed.com" style={{color: '#ffffff'}}>payitfurloughed.com</a></footer>
you're gonna inline this instead of adding to CSS? Are you a monster?

2019-01-18 14:43 UTC, JamesIves commented on client/src/App.js
> +          <footer>Data from <a target="_blank" rel="noopener noreferrer" href="https://payitfurloughed.com" style={{color: '#ffffff'}}>payitfurloughed.com</a></footer>
You're not the boss of me

2019-01-19 15:46 UTC, dwolfand approved these changes
Nice!

2019-01-19 15:46 UTC, merged